project:
  type: website
  output-dir: _site

website:
  title: "SHARP Documentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hermes.qmd
        text: HERMES

format:
  html:
    theme: cosmo
    toc: true
